import Footer from "@/components/new-dashboard/Layout/Footer";
import Header from "@/components/new-dashboard/Layout/Header";
import SideBar from "@/components/new-dashboard/Layout/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./style.css";
import "@/app/globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-bl from-[#340e53] via-[#000533] to-[#010111]   w-screen h-screen overflow-y-scroll">
          <Header />
          <SideBar />
          <div className="pb-12">
          {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
