"use client";
import { useSelector } from "react-redux";
import SingleRecentResumeCard from "./SingleRecentResumeCard";
import { Resume } from "@/store/resumeSlice";
import { useEffect } from "react";
import Script from "next/script";
const RecentResumeCard = ({
  source = "",
  componentRef,
}: {
  source?: string;
  componentRef?: any;
}) => {
  // redux
  const userData = useSelector((state: any) => state.userData);
  const { resumes } = userData;

  return (
    <div className="w-full ">
      <Script type="text/javascript">
        {`
          (function(c,l,a,r,i,t,y){
          c[a]=c[a]function(){(c[a].q=c[a].q[]).push(arguments)};
          t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
          y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
          })(window, document, "clarity", "script", "jum6bniqm4");
        `}
      </Script>
      {/* Google tag (gtag.js) --> */}
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-NDN7TY5F2W"
      />
      <Script>
        {`

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-NDN7TY5F2W');
        `}
      </Script>
      <div className="space-y-4 md:space-y-6">
        <h2 className="text-2xl font-semibold  ">
          Your New Resumes (Generated by AI)
        </h2>
        {!resumes && <p>Loading Resumes...</p>}
        <div className="flex flex-wrap  gap-4 ">
          {resumes &&
            resumes.map((resume: Resume) => {
              if (resume.id) {
                return (
                  <div
                    key={resume.id}
                    className="max-w-[30%] sm:max-w-[50%] xs:max-w-full"
                  >
                    <SingleRecentResumeCard
                      key={resume.id}
                      resume={resume}
                      source={source}
                      componentRef={componentRef}
                    />
                  </div>
                );
              }
            })}
          {resumes && resumes.length === 0 && <p>No Recent Resumes Found</p>}
        </div>
      </div>
    </div>
  );
};

export default RecentResumeCard;
